import type { NextPage } from "next";
import Head from "next/head";
import { Forum } from "../components/forum";
import { useGetForums } from "../hooks/useRequest";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { forums, error } = useGetForums();

  if (error) return <div>Error: {error.message}</div>;
  if (!forums) return <div>Loading...</div>;

  return (
    <div className="py-16 bg-gradient-to-br from-green-50 to-cyan-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container m-auto px-6 text-gray-600 md:px-12 xl:px-6">
        <div className="mb-12 space-y-2 text-center">
          <span className="block w-max mx-auto px-3 py-1.5 border border-green-200 rounded-full bg-green-100 text-green-600">
            Blog
          </span>
          <h2 className="text-2xl text-cyan-900 font-bold md:text-4xl">
            Welcome to Mediavida Stats
          </h2>
          <p className="lg:w-6/12 lg:mx-auto">
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Labore
            voluptate ducimus ipsum recusandae ipsam impedit vitae iusto
            voluptates quisquam a obcaecati ratione iste et ex, necessitatibus
            adipisci sit, inventore voluptatibus.
          </p>
        </div>
        <div className="grid gap-12 lg:grid-cols-2">
          {forums.map((forum: any) => (
            <Forum
              title={forum.title}
              description={forum.description}
              link={forum.link}
            />
          ))}
        </div>
      </div>
    </div>
  );
};

export default Home;
